### ISSUE TITLE
Typo in docs:extensions getSubscribedEvents()

### ISSUE THREAD

**Issue by corpsepk** [roach-php/roach-php.dev#10]
Hello!

Looks like there is a typo in the docs - https://roach-php.dev/docs/extensions

```php
public static function getSubscribedEvents(): array
     {
         return[
             RunFinished::class => ['onRunFinished', 100],
         ];
     }
```

Should not be `RunFinished::class` but `RunFinished::NAME`

**Comment by ksassnowski** [comment]
Thanks for pointing that out. This is fixed in the latest version 👍
