### ISSUE TITLE
link broken

### ISSUE THREAD

**Issue by michabbb** [roach-php/roach-php.dev#9]
the link to `https://roach-php.dev/docs/item-processors` is broken.

example: https://roach-php.dev/docs/items ---> When writing [ItemProcessors](https://roach-php.dev/docs/item-processors), however,...

fyi

**Comment by ksassnowski** [comment]
Thanks for pointing this out. I’ll fix this when I get back from vacation. I’d also appreciate a PR to the documentation repo :)

**Comment by michabbb** [comment]
pardon, how shall i fix a broken link without knowing whats the correct one ? you are funny....
